### PR TITLE
EVA-2885: Update PUT endpoint of contig alias

### PR DESCRIPTION
**Pull request by nitin-ebi**

### CODE REVIEW

**Review by tcezard — APPROVED** [review]
I think it looks good.

**Comment by apriltuesday** [comment]
Diff with other branch (for ease of review): https://github.com/nitin-ebi/contig-alias/compare/update-get...update-put

I think this is missing one of the changes from the ticket, which is that accession length < 15 returns [400](https://github.com/nitin-ebi/contig-alias/blob/update-put/src/main/java/uk/ac/ebi/eva/contigalias/dus/NCBIBrowser.java#L66) and accession not found in NCBI returns [200](https://github.com/nitin-ebi/contig-alias/blob/update-put/src/main/java/uk/ac/ebi/eva/contigalias/dus/NCBIBrowser.java#L110).

Everything else looks good though!

**Comment by nitin-ebi** [comment]
> Diff with other branch (for ease of review): [nitin-ebi/contig-alias@update-get...update-put](https://github.com/nitin-ebi/contig-alias/compare/update-get...update-put)
> 
> I think this is missing one of the changes from the ticket, which is that accession length < 15 returns [400](https://github.com/nitin-ebi/contig-alias/blob/update-put/src/main/java/uk/ac/ebi/eva/contigalias/dus/NCBIBrowser.java#L66) and accession not found in NCBI returns [200](https://github.com/nitin-ebi/contig-alias/blob/update-put/src/main/java/uk/ac/ebi/eva/contigalias/dus/NCBIBrowser.java#L110).
> 
> Everything else looks good though!

1. Added changes for accession length < 15.
2. For accession not found in NCBI it returns optional.empty which is checked later in the code and we return 404 - Assembly not found. Is there a specific reason we want to return 200 here instead of 404. Sorry if this has been discussed earlier, not able to recall.

**Comment by apriltuesday** [comment]
No there's no reason to return 200, sorry if I was confused there... I think it's just that we want to be consistent with the error codes, right now if we try to PUT `short` we get one behaviour, and if we PUT `some-really-long-malformed-nonsense` we get a different behaviour.

The easiest thing is to just return 404 in all these cases I guess, otherwise we have to actually validate the format of the accession and that's probably not this service's job.

**Comment by nitin-ebi** [comment]
> No there's no reason to return 200, sorry if I was confused there... I think it's just that we want to be consistent with the error codes, right now if we try to PUT `short` we get one behaviour, and if we PUT `some-really-long-malformed-nonsense` we get a different behaviour.
> 
> The easiest thing is to just return 404 in all these cases I guess, otherwise we have to actually validate the format of the accession and that's probably not this service's job.

updated to return 404 for every case where assembly could not be found

**Review by apriltuesday — APPROVED** [review]

**Pull request merged**
